
name: movie-api
on:
  push:
    branches: dev
  pull_request:
    branches: [ main, master ]

jobs:
  run_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run_and_test
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: IS_GITHUB_ACTION=true docker-compose up --exit-code-from movie_app
